#!/usr/bin/lua

local uci = require('simple-uci').cursor()
local site = require 'gluon.site'
local vpn_core = require 'gluon.mesh-vpn'

local private_key = uci:get("network", vpn_core.get_interface(), "private_key")

if not private_key or not private_key:match("^" .. ("[%a%d+/]"):rep(42) .. "[AEIMQUYcgkosw480]=$") then
  private_key = "generate"
end

uci:section('network', 'interface', vpn_core.get_interface(), {
  proto = 'wireguard',
  fwmark = 1,
  private_key = private_key,
})

-- Clean up previous configuration
uci:delete_all('wgpeerselector', 'peer', function(peer)
  return peer.preserve ~= '1'
end)

for name, peer in pairs(site.mesh_vpn.wireguard.peers()) do
  uci:section("wgpeerselector", "peer", name, {
    enabled = true,
    endpoint = peer.endpoint,
    public_key = peer.public_key,
    allowed_ips = { "fe80::1/128" },
    ifname = vpn_core.get_interface(),
  })
end

uci:save("wgpeerselector")
uci:save("network")
