#!/bin/sh /etc/rc.common

USE_PROCD=1
START=50

DAEMON=/usr/sbin/autossh
MAXDELAY=10

start_instance() {

	local cfg="$1"
	local index address
	config_get address "$cfg" address
	config_get index "$cfg" index

	procd_open_instance

	procd_set_param env AUTOSSH_GATETIME="30"
	procd_set_param env AUTOSSH_POLL="600"
	procd_set_param env HOME=/root

	procd_set_param command $DAEMON
	# autossh needs two ports for its monitoring
	procd_append_param command -M $((38000+2*index))
	# ssh args follow now
	procd_append_param command -i /etc/dropbear/id_rsa
	procd_append_param command -N -T -y
	procd_append_param command -L "$((37000+index)):localhost:81"
	procd_append_param command "$address"

	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_set_param stderr 1
	procd_set_param stdout 1

	procd_close_instance

}

start_service () {
	if ! test -f /etc/dropbear/id_rsa; then
		dropbearkey -f /etc/dropbear/id_rsa -t rsa
		dropbearkey -f /etc/dropbear/id_rsa -y | grep ssh-rsa > /etc/dropbear/id_rsa.pub
	fi
	config_load gluon-controller
	config_foreach start_instance remote
}
