#!/bin/sh

. /usr/share/libubox/jshn.sh

all_ifaces=$(cat /var/run/gluon-respondd.devs | cut -d" " -f 1)
local_ifaces=$(echo "$all_ifaces" | grep -v br-client)

cat <<EOF
Access-Control-Allow-Origin: *
Content-type: application/json

EOF

json_init
for iface in $local_ifaces
do
	json_add_object "$iface"
	json_add_string address $(cat /sys/class/net/$iface/address)
	json_close_object
done
json_dump
