#!/usr/bin/lua

local uci = require('simple-uci').cursor()
local site = require 'gluon.site'

local cfg = uci:get_first("gluon-controller", "controller") or uci:add("gluon-controller", "controller")
uci:set('gluon-controller', cfg, 'raw_jsonl_url', site.controller.raw_jsonl_url())


local function get_mem_total()
	for line in io.lines('/proc/meminfo') do
		local match = line:match('^MemTotal:%s+(%d+)')
		if match then
			return tonumber(match)
		end
	end
end

local max_requests = 32
if get_mem_total() < 48*1024 then
	max_requests = 16
end

uci:section('uhttpd', 'uhttpd', 'controller', {
	listen_http = { '0.0.0.0:82', '[::]:82' },
	listen_https = {},

	home = '/lib/gluon/controller/www',
	max_requests = max_requests,
	max_connections = 100,
	redirect_https = true,
	rfc1918_filter = true,
	cgi_prefix = '/cgi-bin',
	script_timeout = 60,
	network_timeout = 30,
	http_keepalive = 20,
	tcp_keepalive = true,
})
uci:save('uhttpd')
uci:save('gluon-controller')
uci:save('firewall')
