#!/bin/sh /etc/rc.common

USE_PROCD=1

START=50
SCRIPT=/usr/bin/gluon-fast-acme.sh

start_service()
{
	procd_open_instance
	procd_set_param command $SCRIPT
	procd_set_param file /etc/config/acme
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
