#!/bin/sh

badrequest() {
        echo 'Status: 400 Bad Request'
        echo
        exit 1
}

echo 'Access-Control-Allow-Origin: *'

cat /var/run/gluon-respondd.devs | cut -d" " -f 1 | grep -v br-client | grep -qxF "$QUERY_STRING" || badrequest

CMD="exec /lib/gluon/status-page/providers/neighbours-wifi-signal-levels '$QUERY_STRING'"

exec /usr/sbin/sse-multiplex "$CMD"
